export default ashadha_ashtanika_begins{panghang}{return{}}
export default banada_ashtami{panghang}{return{}}
export default bhanu_saptami{panghang}{return{}}
export default meru_trayodash{panghang}{return{}}
export default ashadha_chaumasi_chaudas{panghang}{return{}}
export default ashadha_ashtahnika_ends{panghang}{return{}}
export default ashadha_ashtanika_begins{panghang}{return{}}
export default ashadha_ashtanika_begins{panghang}{return{}}
export default ashadha_ashtanika_begins{panghang}{return{}}
