export let limited_festival = {
    january:[
    "PAUSHA_PUTRADA_EKADASHI",
    "MAKAR_SANKRANTI",
    "PAUSH_PURNIMA",
    "PONGAL",
    "SAKAT_CHAUTH",
    "SHATTILA_EKADASHI",
    "MAUNI_AMAVAS",
    "VASANT_PANCHAMI",
    "BHISHMA_ASHTAMI",
],
    february :[
        "JAYA_EKADASHI",
        "KUMBHA_SANKRANTI",
        "MAHA_SHIVRATRI",
        "MAGHA_PURNIMA",
        "VIJAYA_EKADASHI",
        "SOMAVATI_AMAVASYA"
    ],
     march : [
        "AMALAKI_EKADASHI",
        "CHHOTI_HOLI",
        "HOLIKA_DAHAN",
        "HOLI",
        "BASODA",
        "PAPMOCHANI_EKADASHI",
        "SHEETALA_ASHATAMI",
        "PAPMOCHANI_EKADASHI",
        "CHAITRA_NAVRATRI",
        "GUDI_PADWA",
        "UGADI",
        "GANGAUR",
        "GAURI_PUJA",
        "YAMUNA_CHHATH",
        "RAMA_NAVAMI",
    ],
    april:[
        "KAMADA_EKADASHI",
        "MESHA_SANKRANTI",
        "SOLAR_NEW_YEAR",
        "HANUMAN_JAYANTI",
        "VARUTHINI_EKADASHI",
        "AKSHAYA_TRITIYA",
        "PARASHURAMA_JAYANTI",
        "SITA_NAVAMI",
    ],
    may:[
        "MOHINI_EKADASHI",
        "NARASIMHA_JAYANTI",
        "VRISHABHA_SANKRANTI",
        "BUDDHA_PURNIMA",
        "CHANDRA_GRAHAN",
        "APARA_EKADASHI",
        "SHANI_JAYANTI",
        "VAT_SAVITRI_VRAT",
        "NIRJALA_EKADASHI",

    ],
     june:[
        "VAT_PURNIMA_VRAT",
        "MITHUNA_SANKRANTI",
        "YOGINI_EKADASHI",
        "JAGANNATH_RATHYATRA",
        "DEVSHAYANI_EKADASHI",

    ],
    july:["GURU_PURNIMA", "KARKA_SANKRANTI", "KAMIKA_EKADASHI"],
     august:[
        "HARIYALI_TEEJ",
        "NAG_PANCHAMI",
        "SHRAVANA_PUTRADA_EKADASHI",
        "RAKHI",
        "RAKSHA_BANDHAN",
        "GAYATRI_JAYANTI",
        "NARALI_PURNIMA",
        "VARALAKSHAMI_VRAT",
        "SIMHA_SANKRANTI",

    ],
    september:[
        "KAJARI_TEEJ",
        "JANMASHTAMI",
        "HARTALIKA_TEEJ",
        "HARTALIKA_TEEJ",
        "GANESH_CHATURTHI",
        "RISHI_PANCHAMI",
        "GAURI_PUJA",
        "PARSVA_EKADASHI",
        "ANANT_CHATURDASHI",
        "GANESH_VISARJAN",
        "KANYA_SANKRANTI",
        "VISHWAKARMA_PUJA",
    ],
    december:[
        "KALABHAIRAV_JAYANTI",
        "VRISCHIKA_SANKRANTI",
        "UTPANNA_EKADASHI",
        "GITA_JAYANTI",
        "MOKSHADA_EKADASHI",
        "DATTATREYA_JAYANTI",
        "DHANU_SANKRANTI",
        "SAPHALA_EKADASHI",
    ],
    november:[
        "KARWA_CHAUTH",
        "AHOI_ASHTAMI",
        "TULA_SANKRANTI",
        "GOVATSA_DWADASHI",
        "RAMA_EKADASHI",
        "DHANTERAS",
        "KALI_CHAUDAS",
        "DIWALI",
        "LAKSHMI_PUJA",
        "NARAK_CHATURDASHI",
        "BHAIYA_DOOJ",
        "GOWARDHAN_PUJA",
        "CHHATH_PUJA",
        "JAGADDHATRI_PUJA",
        "KANSA_VADH",
        "DEVUTTHANA_EKADASHI",
        "TULASI_VIVAH",
        "CHANDRA_GRAHAN",
    ],
     october: [
        "INDIRA_EKADASHI",
        "GHATASTHAPANA",
        "NAVRATRI_BEGINS",
        "SARASWATI_AVAHAN",
        "DURGA_ASHTAMI",
        "SARASWATI_PUJA",
        "MAHA_NAVAMI",
        "DUSSEHRA",
        "VIJAYADASHAMI",
        "PAPANKUSHA_EKADASHI",
        "SHARAD_PURNIMA",
    ]
}


export function LimitedFestival(data,list){
const filteredResults = data.filter(item=> item?.main_festivals == "main");

    // const filteredResults = data.filter(item =>
    //     list.indexOf(item.festival_key) > -1
    // );
  return filteredResults;
}